language: rust
rust:
  - 1.34.2
  - stable
  - nightly
env:
  matrix:
    - FEATURES=''
    - FEATURES='c_api'
script:
  - if [ "${TRAVIS_RUST_VERSION}" == "1.34.2" ]; then
      cargo build -v --features="$FEATURES";
    else
        cargo test -v --features="$FEATURES";
    fi
