[package]
name = "gif"
license = "MIT/Apache-2.0"
version = "0.11.0"
description = "GIF de- and encoder"
authors = ["nwin <nwin@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/image-rs/image-gif"
repository = "https://github.com/image-rs/image-gif"
documentation = "https://docs.rs/gif"
edition = "2018"

exclude = [
    "tests/*",
    "gif-afl/*",
]

[dependencies]
weezl = "0.1.0"
color_quant = "1.0"

[dev-dependencies]
glob = "0.3"
criterion = "0.3.1"

[features]
default = ["raii_no_panic", "std"]

raii_no_panic = []
c_api = ["libc"]
# Reservation for a feature turning off std
std = []

[dependencies.libc]
version = "0.2.1"
optional = true

[[bench]]
name = "decode"
harness = false
